language: node_js

branches:
  only:
  - master

node_js:
  - "7.8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g typescript firebase-tools @angular/cli
  - yarn install

script:
  - npm run build

after_script:
  - firebase deploy --token ${FIREBASE_TOKEN}

notifications:
  slack: scvodigital:FIHvGycOWT1igQcfo1xwAEyj
